version: '2'
services:
 zabbix-server:
  restart: always
  image: zabbix/zabbix-server-pgsql:ubuntu-3.4-latest
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
  links:
   - postgres-server:postgres-server
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000 
   mem_limit: 512m
  env_file:
   - .env_db_pgsql
   - .env_srv
  user: root
  networks:
   zbx_net:
    ipv4_address: 172.16.238.2
    aliases:
     - zabbix-server
     - zabbix-server-pgsql
     - zabbix-server-ubuntu-pgsql
     - zabbix-server-pgsql-ubuntu
  labels:
   com.zabbix.description: "Zabbix server with PostgreSQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "ubuntu"

 zabbix-web-nginx-pgsql:
  restart: always
  image: zabbix/zabbix-web-nginx-pgsql:ubuntu-3.4-latest
  ports:
   - "8081:80"
   - "8443:443"
  links:
   - postgres-server:postgres-server
   - zabbix-server:zabbix-server
  mem_limit: 512m
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
  env_file:
   - .env_db_pgsql
   - .env_web
  user: root
  networks:
   zbx_net:
    ipv4_address: 172.16.238.3
    aliases:
     - zabbix-web-nginx-pgsql
     - zabbix-web-nginx-ubuntu-pgsql
     - zabbix-web-nginx-pgsql-ubuntu
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "ubuntu"

 postgres-server:
  image: postgres:latest
  volumes_from:
   - db_data_pgsql
  volume_driver: local
  env_file:
   - .env_db_pgsql
  user: root
  networks:
   zbx_net:
    ipv4_address: 172.16.238.4
    aliases:
     - postgres-server
     - pgsql-server
     - pgsql-database

 db_data_pgsql:
    image: busybox
    volumes:
    - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw

networks:
  zbx_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
#      - subnet: 2001:3984:3989::/64
#        gateway: 2001:3984:3989::1
